### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property map has not been initialized

### ISSUE THREAD

**Issue by seifane** [suchoX/PlacePicker#39]
Hello I sometimes get this crash.

```
kotlin.UninitializedPropertyAccessException: lateinit property map has not been initialized
	at com.sucho.placepicker.PlacePickerActivity.access$getMap$p(PlacePickerActivity.kt:31)
	at com.sucho.placepicker.PlacePickerActivity$onCreate$2.onClick(PlacePickerActivity.kt:111)
	at android.view.View.performClick(View.java:6300)
	at android.view.View$PerformClick.run(View.java:24941)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```

To me it seems like on low-end devices the map init takes longer and lateinit property doesn't get filled in time.

**Comment by suchoX** [comment]
Good catch. Fixed in `v.1.12`
