### ISSUE TITLE
Random crashes when moving map

### ISSUE THREAD

**Issue by tpoetsch** [suchoX/PlacePicker#4]
This seems to be related to AndroidX

`java.lang.IllegalArgumentException: Illegal state argument: 5
        at com.google.android.material.bottomsheet.BottomSheetBehavior.startSettlingAnimation(BottomSheetBehavior.java:1099)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.startSettlingAnimationPendingLayout(BottomSheetBehavior.java:886)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.setState(BottomSheetBehavior.java:865)
        at com.sucho.placepicker.CurrentPlaceSelectionBottomSheet.toggleBottomSheet(CurrentPlaceSelectionBottomSheet.kt:99)
        at com.sucho.placepicker.CurrentPlaceSelectionBottomSheet.dismissPlaceDetails(CurrentPlaceSelectionBottomSheet.kt:93)
        at com.sucho.placepicker.PlacePickerActivity$onMapReady$1.onCameraMoveStarted(PlacePickerActivity.kt:134)
        at com.google.android.gms.maps.zzu.onCameraMoveStarted(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzu.dispatchTransaction(Unknown Source:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:675)
        at hj.b(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):14)
        at com.google.android.gms.maps.internal.ae.a(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):4)
        at com.google.maps.api.android.lib6.gmm6.api.a.a(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):70)
        at com.google.maps.api.android.lib6.gmm6.vector.ct.a(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):20)
        at com.google.maps.api.android.lib6.gmm6.vector.ct.a(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):139)
        at com.google.maps.api.android.lib6.gmm6.vector.dc.onScroll(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):13)
        at com.google.maps.api.android.lib6.impl.gesture.c.onScroll(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):237)
        at com.google.maps.api.android.lib6.impl.gesture.c.a(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):79)
        at com.google.maps.api.android.lib6.gmm6.vector.af.onTouchEvent(:com.google.android.gms.dynamite_mapsdynamite@17455081@17.4.55 (100400-248795830):76)
        at android.view.View.dispatchTouchEvent(View.java:13484)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:697)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1869)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:655)`

**Comment by suchoX** [comment]
@tpoetsch Thank you for the CrashLog. Will surely fix it. How often does it happen?

**Comment by tpoetsch** [comment]
It happens from time to time when scrolling through the map

**Comment by smaslenko** [comment]
The same crash is happening for me too. Please fix, thank you.

**Comment by suchoX** [comment]
Will Fix it. Give me some time!

**Comment by suchoX** [comment]
@tpoetsch @smaslenko Can you try
`com.sucho:placepicker:0.1.6-alpha01`
If this solves the problem (I am not able to recreate it myself), I will push the lib to the main channel

**Comment by suchoX** [comment]
I probably Fixed it. Feel free to reopen it if it still crashes for you
