### ISSUE TITLE
Error when I try to startActivityForResult

### ISSUE THREAD

**Issue by Ivrean** [suchoX/PlacePicker#5]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.astonsoft.android.essentialpim/com.sucho.placepicker.PlacePickerActivity}: android.view.InflateException: Binary XML file line #118: Binary XML file line #118: Error inflating class com.google.android.material.card.MaterialCardView

I follow the instructions, but I get this error. Sorry for the question, but I can not solve it myself.

**Comment by suchoX** [comment]
@Ivrean Are you using AndroidX?

**Comment by Ivrean** [comment]
Yes, I did the migration. But I think I have confusion with the styles. Now I am updating the styles and I hope this solves my problem.

**Comment by suchoX** [comment]
@Ivrean Keep me updated. I am looking into the issue as well.

**Comment by Ivrean** [comment]
I made a change, but the error still appears.

Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:78)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:121)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:111)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:532) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at com.sucho.placepicker.PlacePickerActivity.onCreate(PlacePickerActivity.kt:53)

**Comment by suchoX** [comment]
@Ivrean I probably fixed the issue. Feel free to reopen this if it still crashes for you. In that case I will remove the PlacePickerActivity from my Manifest and would ask your app to mention the PlacePickerActivity in your manifest file. That way, you can give your own style to the activity
